from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import openpyxl
from openpyxl.styles import (
    Font, Fill, PatternFill, Alignment
)
from openpyxl.chart import BarChart, Reference
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor as PptxRGB
import os, json, subprocess
from datetime import datetime

class DocumentEngine:

    def create_docx(self, title: str,
                    content: str,
                    path: str = None) -> str:
        """
        Create a .docx Word document.
        content can be plain text or JSON sections.
        """
        doc = Document()
        
        # Title style
        heading = doc.add_heading(title, 0)
        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add timestamp
        doc.add_paragraph(
            f"Generated by N.O.V.A — "
            f"{datetime.now().strftime('%B %d, %Y')}"
        ).style = doc.styles['Subtitle']
        
        doc.add_paragraph("")
        
        # Parse content — support sections
        try:
            sections = json.loads(content)
            if isinstance(sections, list):
                for section in sections:
                    if section.get("heading"):
                        doc.add_heading(
                            section["heading"], 1
                        )
                    if section.get("text"):
                        doc.add_paragraph(
                            section["text"]
                        )
                    if section.get("bullets"):
                        for b in section["bullets"]:
                            doc.add_paragraph(
                                b, style='List Bullet'
                            )
                    if section.get("table"):
                        t = section["table"]
                        table = doc.add_table(
                            rows=1,
                            cols=len(t["headers"])
                        )
                        table.style = 'Table Grid'
                        hdr = table.rows[0].cells
                        for i, h in enumerate(
                            t["headers"]
                        ):
                            hdr[i].text = h
                            hdr[i].paragraphs[0]\
                                .runs[0].font.bold = True
                        for row in t.get("rows", []):
                            cells = table.add_row()\
                                .cells
                            for i, val in enumerate(
                                row
                            ):
                                cells[i].text = str(val)
        except (json.JSONDecodeError, KeyError, TypeError) as e:
            print(f"[DocEngine] JSON parse failed, using plain text: {e}")
            # Plain text — split into paragraphs
            for para in content.split('\n\n'):
                if para.strip():
                    if para.startswith('# '):
                        doc.add_heading(
                            para[2:], 1
                        )
                    elif para.startswith('## '):
                        doc.add_heading(
                            para[3:], 2
                        )
                    elif para.startswith('- '):
                        for line in para.split('\n'):
                            if line.startswith('- '):
                                doc.add_paragraph(
                                    line[2:],
                                    style='List Bullet'
                                )
                    else:
                        doc.add_paragraph(para)
        
        if not path:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            path = f"~/Desktop/nova_{ts}.docx"
        
        expanded = os.path.expanduser(path)
        doc.save(expanded)
        
        # Open in Word, fallback to Pages
        import subprocess
        result = subprocess.run(
            ['open', '-a', 'Microsoft Word', expanded],
            capture_output=True
        )
        if result.returncode != 0:
            subprocess.Popen(
                ['open', '-a', 'Pages', expanded]
            )
        print(f"[DocEngine] Opened: {expanded}")
        return f"Document created and opened: {path}"
    
    def create_xlsx(self, title: str,
                    data: list,
                    path: str = None,
                    add_chart: bool = True) -> str:
        """
        Create .xlsx spreadsheet with data + chart.
        data: list of dicts or list of lists
        """
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = title[:31]
        
        # Title row
        ws['A1'] = title
        ws['A1'].font = Font(
            bold=True, size=14
        )
        ws['A1'].alignment = Alignment(
            horizontal='center'
        )
        
        if not data:
            path = path or f"~/Desktop/nova_sheet.xlsx"
            expanded = os.path.expanduser(path)
            wb.save(expanded)
            return f"Spreadsheet created: {path}"
        
        # Headers
        start_row = 3
        if isinstance(data[0], dict):
            headers = list(data[0].keys())
            for col, header in enumerate(
                headers, 1
            ):
                cell = ws.cell(
                    row=start_row,
                    column=col,
                    value=header
                )
                cell.font = Font(bold=True)
                cell.fill = PatternFill(
                    "solid", 
                    fgColor="1a2a2a"
                )
            
            for row_idx, row_data in enumerate(
                data, start_row + 1
            ):
                for col_idx, key in enumerate(
                    headers, 1
                ):
                    ws.cell(
                        row=row_idx,
                        column=col_idx,
                        value=row_data.get(key, "")
                    )
        else:
            # List of lists
            for row_idx, row in enumerate(
                data, start_row
            ):
                for col_idx, val in enumerate(
                    row, 1
                ):
                    ws.cell(
                        row=row_idx,
                        column=col_idx,
                        value=val
                    )
        
        # Auto-width columns
        for col in ws.columns:
            max_len = max(
                len(str(cell.value or ""))
                for cell in col
            )
            ws.column_dimensions[
                col[0].column_letter
            ].width = min(max_len + 4, 40)
        
        # Add bar chart if numeric data
        if add_chart and len(data) > 1:
            try:
                chart = BarChart()
                chart.title = title
                chart.style = 10
                data_ref = Reference(
                    ws,
                    min_col=2,
                    min_row=start_row,
                    max_row=start_row + len(data)
                )
                chart.add_data(
                    data_ref, titles_from_data=True
                )
                ws.add_chart(chart, "A15")
            except (KeyError, TypeError, ValueError) as e:
                print(f"[DocEngine] Chart creation failed: {e}")
        
        if not path:
            ts = datetime.now().strftime(
                "%Y%m%d_%H%M%S"
            )
            path = f"~/Desktop/nova_{ts}.xlsx"
        
        expanded = os.path.expanduser(path)
        import subprocess
        result = subprocess.run(
            ['open', '-a', 'Microsoft Excel', expanded],
            capture_output=True
        )
        if result.returncode != 0:
            subprocess.Popen(
                ['open', '-a', 'Numbers', expanded]
            )
        print(f"[DocEngine] Opened: {expanded}")
        return f"Spreadsheet created and opened: {path}"
    
    def create_pptx(self, title: str,
                    slides: list,
                    path: str = None) -> str:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        import os, subprocess
        from datetime import datetime
        
        prs = Presentation()
        
        # Title slide
        title_slide = prs.slides.add_slide(
            prs.slide_layouts[0]
        )
        title_slide.shapes.title.text = title
        try:
            title_slide.placeholders[1].text = (
                f"Generated by N.O.V.A — "
                f"{datetime.now().strftime('%B %d, %Y')}"
            )
        except (KeyError, IndexError) as e:
            print(f"[DocEngine] Subtitle placeholder not found: {e}")
        
        # Content slides
        for slide_data in slides:
            try:
                slide = prs.slides.add_slide(
                    prs.slide_layouts[1]
                )
                # Set title safely
                try:
                    slide.shapes.title.text = (
                        slide_data.get("title", "")
                    )
                except (KeyError, IndexError, AttributeError) as e:
                    print(f"[DocEngine] Slide title set failed: {e}")
                
                # Set content safely
                try:
                    tf = slide.placeholders[1]\
                         .text_frame
                    tf.clear()
                    
                    if slide_data.get("content"):
                        p = tf.paragraphs[0]
                        p.text = slide_data["content"]
                        p.font.size = Pt(18)
                    
                    for bullet in slide_data.get(
                        "bullets", []
                    ):
                        p = tf.add_paragraph()
                        p.text = str(bullet)
                        p.level = 1
                        p.font.size = Pt(16)
                except (KeyError, IndexError, AttributeError) as e:
                    print(f"[DocEngine] Slide content set failed: {e}")
            except Exception as e:
                print(f"[DocEngine] Slide error: {e}")
                continue
        
        # Generate path
        if not path:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            path = f"~/Desktop/nova_{ts}.pptx"
        
        expanded = os.path.expanduser(path)
        
        # Ensure directory exists
        os.makedirs(
            os.path.dirname(expanded),
            exist_ok=True
        )
        
        # Save with error handling
        try:
            prs.save(expanded)
            print(f"[DocEngine] Saved: {expanded}")
        except Exception as e:
            print(f"[DocEngine] Save failed: {e}")
            return f"Presentation save failed: {e}"
        
        # Verify file exists before opening
        if not os.path.exists(expanded):
            return f"File was not created at {expanded}"
        
        file_size = os.path.getsize(expanded)
        print(f"[DocEngine] File size: {file_size} bytes")
        
        # Open with Keynote fallback
        result = subprocess.run(
            ['open', '-a', 'Microsoft PowerPoint',
             expanded],
            capture_output=True
        )
        if result.returncode != 0:
            subprocess.Popen(
                ['open', '-a', 'Keynote', expanded]
            )
        
        return f"Presentation created: {path}"

    def create_pdf(self, title: str,
                   content: str,
                   path: str = None) -> str:
        """
        Create a styled .pdf document using fpdf2.
        content can be plain text or JSON sections.
        """
        from fpdf import FPDF

        def _sanitize(text):
            """Strip non-latin1 chars that Helvetica can't render."""
            replacements = {
                '\u2022': '-', '\u2013': '-', '\u2014': '-',
                '\u2018': "'", '\u2019': "'", '\u201c': '"', '\u201d': '"',
                '\u2026': '...', '\u2192': '->', '\u2190': '<-',
                '\u2713': '[x]', '\u2717': '[ ]', '\u2605': '*',
            }
            for k, v in replacements.items():
                text = text.replace(k, v)
            return text.encode('latin-1', 'replace').decode('latin-1')

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)

        # ── Title page ──────────────────────────
        pdf.add_page()
        pdf.set_fill_color(20, 20, 35)
        pdf.rect(0, 0, 210, 297, 'F')
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Helvetica', 'B', 28)
        pdf.ln(80)
        pdf.cell(0, 15, title, align='C', new_x='LMARGIN', new_y='NEXT')
        pdf.set_font('Helvetica', '', 12)
        pdf.set_text_color(180, 180, 200)
        pdf.ln(10)
        pdf.cell(0, 8,
                 f"Generated by N.O.V.A  |  {datetime.now().strftime('%B %d, %Y')}",
                 align='C', new_x='LMARGIN', new_y='NEXT')

        # ── Content pages ───────────────────────
        pdf.add_page()
        pdf.set_fill_color(255, 255, 255)
        pdf.rect(0, 0, 210, 297, 'F')
        pdf.set_text_color(30, 30, 30)

        def _heading(text, level=1):
            size = 18 if level == 1 else 14
            pdf.set_font('Helvetica', 'B', size)
            pdf.set_text_color(20, 60, 120)
            pdf.ln(6 if level == 1 else 4)
            pdf.multi_cell(0, 8, text)
            pdf.set_text_color(30, 30, 30)
            pdf.ln(2)

        def _body(text):
            pdf.set_font('Helvetica', '', 11)
            pdf.multi_cell(0, 6, text)
            pdf.ln(3)

        def _bullet(text):
            pdf.set_font('Helvetica', '', 11)
            x = pdf.get_x()
            pdf.cell(8, 6, '-')
            pdf.multi_cell(0, 6, text)
            pdf.ln(1)

        # Parse content
        try:
            sections = json.loads(content)
            if isinstance(sections, list):
                for section in sections:
                    if section.get('heading'):
                        _heading(section['heading'], 1)
                    if section.get('subheading'):
                        _heading(section['subheading'], 2)
                    if section.get('text'):
                        _body(section['text'])
                    for b in section.get('bullets', []):
                        _bullet(str(b))
        except (json.JSONDecodeError, KeyError, TypeError):
            # Plain text fallback
            for para in content.split('\n\n'):
                para = para.strip()
                if not para:
                    continue
                if para.startswith('# '):
                    _heading(para[2:], 1)
                elif para.startswith('## '):
                    _heading(para[3:], 2)
                elif para.startswith('- '):
                    for line in para.split('\n'):
                        if line.strip().startswith('- '):
                            _bullet(line.strip()[2:])
                else:
                    _body(para)

        # Save
        if not path:
            ts = datetime.now().strftime('%Y%m%d_%H%M%S')
            path = f'~/Desktop/nova_{ts}.pdf'

        expanded = os.path.expanduser(path)
        os.makedirs(os.path.dirname(expanded), exist_ok=True)
        pdf.output(expanded)

        # Open in default PDF viewer
        subprocess.Popen(['open', expanded])
        print(f'[DocEngine] PDF created: {expanded}')
        return f'PDF created and opened: {path}'
    
    async def generate_document_with_llm(
            self, instruction: str,
            doc_type: str) -> str:
        """
        Use LLM to generate document content
        then create the actual file.
        """
        print(f"[DocEngine] Generating {doc_type}: "
              f"{instruction[:50]}")
        from llm import _chat
        
        TYPE_PROMPTS = {
            "docx": (
                "Generate a professional Word document "
                "structure as JSON array of sections. "
                "Each section: {heading, text, bullets?,"
                " table?}. Task: "
            ),
            "xlsx": (
                "Generate spreadsheet data as JSON array"
                " of objects with consistent keys. "
                "Task: "
            ),
            "pptx": (
                "Generate presentation slides as JSON "
                "array. Each slide: {title, content, "
                "bullets: []}. Make 5-7 slides. Task: "
            ),
            "pdf": (
                "Generate a detailed study notes document as a "
                "JSON array of sections. Each section must have: "
                "{heading, text, bullets: []}. "
                "Include 8-15 well-structured sections with "
                "comprehensive, detailed explanations in the "
                "'text' field and key points as 'bullets'. "
                "Be thorough and educational. Task: "
            )
        }
        
        prompt = (
            TYPE_PROMPTS.get(doc_type, "") +
            instruction +
            "\n\nReturn ONLY valid JSON. No explanation."
        )
        
        try:
            content = _chat(
                system="You are a document generation assistant. Return ONLY valid JSON.",
                user=prompt,
                json_mode=True
            )
            
            # Clean JSON
            import re
            json_match = re.search(
                r'\[.*\]', content, re.DOTALL
            )
            if json_match:
                content = json_match.group(0)
            
            title = instruction[:50].title()
            
            if doc_type == "docx":
                return self.create_docx(
                    title, content
                )
            elif doc_type == "xlsx":
                data = json.loads(content)
                return self.create_xlsx(
                    title, data
                )
            elif doc_type == "pptx":
                slides = json.loads(content)
                return self.create_pptx(
                    title, slides
                )
            elif doc_type == "pdf":
                return self.create_pdf(
                    title, content
                )
        except Exception as e:
            return f"Document generation failed: {e}"

doc_engine = DocumentEngine()
