import os
import re
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

# ── Color scheme ──
PRIMARY = RGBColor(0x1A, 0x1A, 0x2E)
ACCENT  = RGBColor(0xE9, 0x45, 0x60)
LIGHT_GRAY = RGBColor(0x66, 0x66, 0x66)

# ── Documents output directory ──
DOCS_DIR = Path(__file__).resolve().parent.parent / "documents"
DOCS_DIR.mkdir(exist_ok=True)


def _add_horizontal_rule(doc):
    """Add a horizontal rule to the document."""
    p = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), '6')
    bottom.set(qn('w:space'), '1')
    bottom.set(qn('w:color'), 'E94560')
    pBdr.append(bottom)
    pPr.append(pBdr)
    return p


def _set_cell_shading(cell, color_hex: str):
    """Set background shading on a table cell."""
    shading = OxmlElement('w:shd')
    shading.set(qn('w:fill'), color_hex)
    shading.set(qn('w:val'), 'clear')
    cell._tc.get_or_add_tcPr().append(shading)


def _configure_styles(doc):
    """Set up custom document styles."""
    style = doc.styles

    # Heading 1
    h1 = style['Heading 1']
    h1_font = h1.font
    h1_font.size = Pt(18)
    h1_font.color.rgb = PRIMARY
    h1_font.bold = True
    h1.paragraph_format.space_after = Pt(8)
    h1.paragraph_format.space_before = Pt(16)

    # Heading 2
    h2 = style['Heading 2']
    h2_font = h2.font
    h2_font.size = Pt(14)
    h2_font.color.rgb = ACCENT
    h2_font.bold = True
    h2.paragraph_format.space_after = Pt(6)
    h2.paragraph_format.space_before = Pt(12)

    # Normal / Body
    normal = style['Normal']
    normal_font = normal.font
    normal_font.size = Pt(11)
    normal.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    normal.paragraph_format.line_spacing = 1.5
    normal.paragraph_format.space_after = Pt(6)

    return style


def _add_header(doc, topic: str):
    """Add header with topic name and NOVA branding."""
    section = doc.sections[0]
    header = section.header
    header.is_linked_to_previous = False

    # Create a table for left-right alignment in header
    htable = header.add_table(1, 2, width=Inches(6.5))
    htable.autofit = True

    # Left cell: topic
    left_cell = htable.cell(0, 0)
    left_p = left_cell.paragraphs[0]
    left_run = left_p.add_run(topic)
    left_run.font.size = Pt(8)
    left_run.font.color.rgb = LIGHT_GRAY
    left_p.alignment = WD_ALIGN_PARAGRAPH.LEFT

    # Right cell: branding
    right_cell = htable.cell(0, 1)
    right_p = right_cell.paragraphs[0]
    right_run = right_p.add_run("Generated by N.O.V.A")
    right_run.font.size = Pt(8)
    right_run.font.color.rgb = LIGHT_GRAY
    right_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT

    # Bottom border on header
    for cell in htable.row_cells(0):
        tc = cell._tc
        tcPr = tc.get_or_add_tcPr()
        tcBorders = OxmlElement('w:tcBorders')
        bottom = OxmlElement('w:bottom')
        bottom.set(qn('w:val'), 'single')
        bottom.set(qn('w:sz'), '4')
        bottom.set(qn('w:color'), 'E94560')
        tcBorders.append(bottom)
        tcPr.append(tcBorders)


def _add_footer(doc):
    """Add footer with page number and date."""
    section = doc.sections[0]
    footer = section.footer
    footer.is_linked_to_previous = False

    # Create table for layout
    ftable = footer.add_table(1, 2, width=Inches(6.5))
    ftable.autofit = True

    # Left cell: page number
    left_cell = ftable.cell(0, 0)
    left_p = left_cell.paragraphs[0]
    left_p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Add page number field
    run = left_p.add_run()
    fldChar1 = OxmlElement('w:fldChar')
    fldChar1.set(qn('w:fldCharType'), 'begin')
    run._r.append(fldChar1)

    instrText = OxmlElement('w:instrText')
    instrText.set(qn('xml:space'), 'preserve')
    instrText.text = ' PAGE '
    run._r.append(instrText)

    fldChar2 = OxmlElement('w:fldChar')
    fldChar2.set(qn('w:fldCharType'), 'end')
    run._r.append(fldChar2)
    run.font.size = Pt(8)
    run.font.color.rgb = LIGHT_GRAY

    # Right cell: date
    right_cell = ftable.cell(0, 1)
    right_p = right_cell.paragraphs[0]
    date_run = right_p.add_run(
        datetime.now().strftime("%B %d, %Y")
    )
    date_run.font.size = Pt(8)
    date_run.font.color.rgb = LIGHT_GRAY
    right_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT


def _parse_sections(content: str):
    """Split content into (heading, body_lines) tuples."""
    sections = []
    current_heading = "Overview"
    current_body = []

    for line in content.split('\n'):
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith('## '):
            if current_body:
                sections.append((current_heading, current_body))
            current_heading = stripped.lstrip('#').strip()
            current_body = []
        elif stripped.startswith('# '):
            if current_body:
                sections.append((current_heading, current_body))
            current_heading = stripped.lstrip('#').strip()
            current_body = []
        else:
            current_body.append(stripped)

    if current_body:
        sections.append((current_heading, current_body))

    if not sections:
        paragraphs = [p.strip() for p in content.split('\n\n') if p.strip()]
        if len(paragraphs) <= 1:
            sections = [("Overview", content.split('\n'))]
        else:
            for i, para in enumerate(paragraphs):
                sections.append((f"Section {i + 1}", para.split('\n')))

    return sections


def create_document(topic: str, content: str) -> str:
    """
    Create a professional Word document.

    Returns: absolute file path of the generated DOCX.
    """
    date_str = datetime.now().strftime("%Y-%m-%d")
    safe_name = re.sub(r'[^\w\s-]', '', topic).strip().replace(' ', '_')[:60]
    filename = f"{safe_name}_{date_str}.docx"
    filepath = str(DOCS_DIR / filename)

    doc = Document()

    # ── Page margins ──
    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

    # ── Configure styles ──
    _configure_styles(doc)

    # ── Header & Footer ──
    _add_header(doc, topic)
    _add_footer(doc)

    # ════════════════════════════════════════════
    # COVER PAGE
    # ════════════════════════════════════════════

    # NOVA branding
    nova_p = doc.add_paragraph()
    nova_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    nova_run = nova_p.add_run("N.O.V.A")
    nova_run.font.size = Pt(36)
    nova_run.font.color.rgb = ACCENT
    nova_run.font.bold = True

    doc.add_paragraph()  # spacer

    # Title
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_p.add_run(topic)
    title_run.font.size = Pt(24)
    title_run.font.color.rgb = PRIMARY
    title_run.font.bold = True

    doc.add_paragraph()  # spacer

    # Subtitle
    sub_p = doc.add_paragraph()
    sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = sub_p.add_run("Comprehensive Report")
    sub_run.font.size = Pt(14)
    sub_run.font.color.rgb = LIGHT_GRAY

    # Date
    date_p = doc.add_paragraph()
    date_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_run = date_p.add_run(
        datetime.now().strftime("%B %d, %Y")
    )
    date_run.font.size = Pt(12)
    date_run.font.color.rgb = LIGHT_GRAY

    _add_horizontal_rule(doc)
    doc.add_page_break()

    # ════════════════════════════════════════════
    # TABLE OF CONTENTS
    # ════════════════════════════════════════════

    doc.add_heading("Table of Contents", level=1)
    sections = _parse_sections(content)

    for idx, (heading, _) in enumerate(sections, 1):
        toc_p = doc.add_paragraph()
        toc_run = toc_p.add_run(f"{idx}. {heading}")
        toc_run.font.size = Pt(12)
        toc_run.font.color.rgb = PRIMARY

    doc.add_page_break()

    # ════════════════════════════════════════════
    # CONTENT PAGES
    # ════════════════════════════════════════════

    for heading, body_lines in sections:
        doc.add_heading(heading, level=1)

        for line in body_lines:
            line = line.strip()
            if not line:
                continue

            # Sub-heading detection
            if line.startswith('### '):
                doc.add_heading(line.lstrip('#').strip(), level=2)
                continue

            # Bullet point
            if line.startswith('- ') or line.startswith('• '):
                bullet_text = line.lstrip('-•').strip()
                bullet_p = doc.add_paragraph(
                    bullet_text, style='List Bullet'
                )
                for run in bullet_p.runs:
                    run.font.size = Pt(11)
                continue

            # Regular body text
            body_p = doc.add_paragraph(line)
            body_p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            for run in body_p.runs:
                run.font.size = Pt(11)
            body_p.paragraph_format.line_spacing = 1.5

    # ── Save ──
    doc.save(filepath)
    print(f"[DOCXTool] ✓ Document created: {filepath}")
    return filepath
