import os
import re
import json
from datetime import datetime
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

# ── Color scheme ──
PRIMARY = RGBColor(0x1A, 0x1A, 0x2E)
ACCENT  = RGBColor(0xE9, 0x45, 0x60)
WHITE   = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT   = RGBColor(0xF5, 0xF5, 0xF5)
DARK_GRAY = RGBColor(0x66, 0x66, 0x66)
WATERMARK_GRAY = RGBColor(0xCC, 0xCC, 0xCC)

# ── Documents output directory ──
DOCS_DIR = Path(__file__).resolve().parent.parent / "documents"
DOCS_DIR.mkdir(exist_ok=True)

# Slide dimensions (standard 16:9)
SLIDE_WIDTH  = Inches(13.333)
SLIDE_HEIGHT = Inches(7.5)


def _set_slide_bg(slide, color: RGBColor):
    """Set a slide's background to a solid color."""
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_shape(slide, left, top, width, height, fill_color):
    """Add a colored rectangle shape to a slide."""
    from pptx.util import Emu as _Emu
    shape = slide.shapes.add_shape(
        1,  # MSO_SHAPE.RECTANGLE
        left, top, width, height
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill_color
    shape.line.fill.background()
    return shape


def _add_textbox(slide, text, left, top, width, height,
                 font_size=18, color=PRIMARY, bold=False,
                 alignment=PP_ALIGN.LEFT):
    """Add a text box to a slide."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(font_size)
    p.font.color.rgb = color
    p.font.bold = bold
    p.alignment = alignment
    return txBox


def _structure_content_with_llm(topic: str, content: str,
                                 num_slides: int = 10) -> list:
    """Use LLM to structure content into slide data."""
    try:
        import sys
        sys.path.append(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        )
        from llm import _chat

        system_prompt = (
            f"Convert this content into exactly {num_slides} slides. "
            "Return ONLY a JSON array:\n"
            '[{"title": "...", "bullets": ["...", "...", "..."], '
            '"speaker_notes": "..."}]\n'
            "Max 4 bullets per slide. First slide is title slide. "
            "Last slide is 'Thank You / Summary'."
        )
        user_msg = f"Topic: {topic}\nContent: {content}"

        raw = _chat(system=system_prompt, user=user_msg,
                     temperature=0.3, json_mode=False)

        # Extract JSON from response
        # Try to find JSON array in the response
        json_match = re.search(r'\[.*\]', raw, re.DOTALL)
        if json_match:
            return json.loads(json_match.group())

        return json.loads(raw)

    except Exception as e:
        print(f"[PPTXTool] LLM structuring failed: {e}")
        # Fallback: create basic slides from content
        return _fallback_slides(topic, content, num_slides)


def _fallback_slides(topic: str, content: str,
                      num_slides: int) -> list:
    """Create basic slide structure without LLM."""
    slides = [
        {
            "title": topic,
            "bullets": [
                "A Comprehensive Overview",
                f"Generated {datetime.now().strftime('%B %d, %Y')}",
                "Generated by N.O.V.A"
            ],
            "speaker_notes": f"Title slide for {topic}"
        }
    ]

    # Split content into chunks
    paragraphs = [p.strip() for p in content.split('\n\n') if p.strip()]
    if not paragraphs:
        paragraphs = [p.strip() for p in content.split('\n') if p.strip()]

    # Create content slides
    chunk_size = max(1, len(paragraphs) // (num_slides - 2))
    slide_num = 1
    for i in range(0, len(paragraphs), chunk_size):
        if slide_num >= num_slides - 1:
            break
        chunk = paragraphs[i:i + chunk_size]
        bullets = []
        for line in chunk:
            clean = line.lstrip('#-•* ').strip()
            if clean:
                bullets.append(clean[:120])
        if bullets:
            heading = bullets[0][:50] if bullets else f"Section {slide_num}"
            slides.append({
                "title": heading,
                "bullets": bullets[:4],
                "speaker_notes": " ".join(bullets)
            })
            slide_num += 1

    # Pad if needed
    while len(slides) < num_slides - 1:
        slides.append({
            "title": f"Section {len(slides)}",
            "bullets": ["Content to be expanded"],
            "speaker_notes": ""
        })

    # Thank you slide
    slides.append({
        "title": "Thank You",
        "bullets": [
            "Questions & Discussion",
            f"Generated by N.O.V.A on {datetime.now().strftime('%B %d, %Y')}",
            "For more information, contact the author"
        ],
        "speaker_notes": "Closing slide"
    })

    return slides


def create_presentation(topic: str, content: str,
                         num_slides: int = 10) -> str:
    """
    Create a professional PowerPoint presentation.

    Returns: absolute file path of the generated PPTX.
    """
    date_str = datetime.now().strftime("%Y-%m-%d")
    safe_name = re.sub(r'[^\w\s-]', '', topic).strip().replace(' ', '_')[:60]
    filename = f"{safe_name}_{date_str}.pptx"
    filepath = str(DOCS_DIR / filename)

    prs = Presentation()
    prs.slide_width = SLIDE_WIDTH
    prs.slide_height = SLIDE_HEIGHT

    # Get structured content
    slide_data = _structure_content_with_llm(topic, content, num_slides)

    for idx, slide_info in enumerate(slide_data):
        slide_layout = prs.slide_layouts[6]  # Blank layout
        slide = prs.slides.add_slide(slide_layout)

        title = slide_info.get("title", "")
        bullets = slide_info.get("bullets", [])
        notes = slide_info.get("speaker_notes", "")

        if idx == 0:
            # ══════ TITLE SLIDE ══════
            _set_slide_bg(slide, PRIMARY)

            # Large white title
            _add_textbox(
                slide, title,
                Inches(1.5), Inches(2.0),
                Inches(10), Inches(2),
                font_size=44, color=WHITE, bold=True,
                alignment=PP_ALIGN.CENTER
            )

            # Subtitle
            subtitle_text = (
                f"{datetime.now().strftime('%B %d, %Y')}  |  "
                f"Generated by N.O.V.A"
            )
            _add_textbox(
                slide, subtitle_text,
                Inches(1.5), Inches(4.2),
                Inches(10), Inches(1),
                font_size=18, color=LIGHT,
                alignment=PP_ALIGN.CENTER
            )

            # Accent bottom bar
            _add_shape(
                slide,
                Inches(0), Inches(6.8),
                SLIDE_WIDTH, Inches(0.15),
                ACCENT
            )

        elif idx == len(slide_data) - 1:
            # ══════ LAST SLIDE (Thank You) ══════
            _set_slide_bg(slide, PRIMARY)

            _add_textbox(
                slide, title,
                Inches(1.5), Inches(1.8),
                Inches(10), Inches(1.5),
                font_size=40, color=WHITE, bold=True,
                alignment=PP_ALIGN.CENTER
            )

            # Summary bullets
            bullet_text = "\n".join(f"• {b}" for b in bullets)
            _add_textbox(
                slide, bullet_text,
                Inches(2.5), Inches(3.5),
                Inches(8), Inches(3),
                font_size=16, color=LIGHT,
                alignment=PP_ALIGN.CENTER
            )

            # Accent line
            _add_shape(
                slide,
                Inches(4), Inches(3.2),
                Inches(5), Inches(0.05),
                ACCENT
            )

        else:
            # ══════ CONTENT SLIDES ══════
            _set_slide_bg(slide, WHITE)

            # Title bar at top
            _add_shape(
                slide,
                Inches(0), Inches(0),
                SLIDE_WIDTH, Inches(1.2),
                PRIMARY
            )

            # Title text in bar
            _add_textbox(
                slide, title,
                Inches(1.0), Inches(0.15),
                Inches(11), Inches(0.9),
                font_size=28, color=WHITE, bold=True,
                alignment=PP_ALIGN.LEFT
            )

            # Accent left border line
            _add_shape(
                slide,
                Inches(0.8), Inches(1.6),
                Inches(0.06), Inches(4.5),
                ACCENT
            )

            # Bullet points in body
            bullet_text = "\n\n".join(f"• {b}" for b in bullets)
            _add_textbox(
                slide, bullet_text,
                Inches(1.2), Inches(1.8),
                Inches(10.5), Inches(4.5),
                font_size=18, color=PRIMARY,
                alignment=PP_ALIGN.LEFT
            )

            # Slide number bottom right
            _add_textbox(
                slide, str(idx + 1),
                Inches(12.0), Inches(6.9),
                Inches(1), Inches(0.5),
                font_size=12, color=ACCENT, bold=True,
                alignment=PP_ALIGN.RIGHT
            )

            # N.O.V.A watermark bottom left
            _add_textbox(
                slide, "N.O.V.A",
                Inches(0.5), Inches(6.9),
                Inches(2), Inches(0.5),
                font_size=10, color=WATERMARK_GRAY,
                alignment=PP_ALIGN.LEFT
            )

        # Speaker notes
        if notes:
            notes_slide = slide.notes_slide
            notes_slide.notes_text_frame.text = notes

    prs.save(filepath)
    print(f"[PPTXTool] ✓ Presentation created: {filepath}")
    return filepath
